parse_config:
  zmk_preamble: "#include <zmk-helpers/key-labels/36.h>"
  zmk_additional_includes:
    - "modules/zmk/helpers/include"

draw_config:
  footer_text: "ficcdaf/zmk-config"
  dark_mode: true
